### PR TITLE
Updated the documentation after testing the flask app using the push …

### PR DESCRIPTION
**Pull request by bahramr**
…and pull methods  on an AKS cluster deployed using the Construction Helper

### CODE REVIEW

**Review by Buchatech — APPROVED** [review]

**Review by Buchatech — COMMENTED** [review]
Sync Policy: should be set to automatic. 
Also you should set Argo CD to automatically create the namespace.

**Comment by bahramr** [comment]
For the pull option (Argo CD), I did not mention creating the namespace. We only do it for the push option. Am I missing something?
I will change the sync policy.
Also in push workflow, the name of the ACR is hard coded in the deployment yaml file. Not sure how we can address that without having to update the file in the repo and do a commit as we do with the pull option. Any idea?

**Comment by Buchatech** [comment]
It is best to create a namespace in Argo CD so the app does not end up in the default namespace. 

In push you should be prompted for the ACR name at the time of running the workflow therefore it is dynamic. If someone removed that please change it back.

**Comment by bahramr** [comment]
We capture the ACR name at the time of running the workflow and we set it in the deployment.yaml file through a commit in the [App-Flask-GitOps.yml](https://github.com/Azure/aks-baseline-automation/blob/main/.github/workflows/App-Flask-GitOps.yml) workflow but we don't do that in the [App-Flask-DockerBuild.yml](https://github.com/Azure/aks-baseline-automation/blob/main/.github/workflows/App-Flask-DockerBuild.yml) workflow. I was wondering if we could find an alternate way of setting it when deploying the app? Too bad that the k8s-deploy Action only supports setting the image tag.

**Pull request merged**
