### PR TITLE
Carmodyquinn traefik

### PR DESCRIPTION
**Pull request by carmodyquinnms**
Updates include everything for User Story 22394

Changes include:

1. Fix broken flux implementation to work with this repo rather than old one
2. Update k8s version to 1.23.8
3. Update machine profile to Standard_DS3_v2, the last machines could barely support core component requests
4. Create workflow that allows user to create AKS Cluster only rather than entire hub/spoke arch and stack
5. Create workflow to create ingress certs and import into AKV
6. Create workflow that will import traefik into ACR and deploy appropriate traefik files into directories so that flux can then deploy to the cluster.
7. Have tested all features and compared to main

### CODE REVIEW

**Review by MattLeach25 — APPROVED** [review]

**Comment by Gordonby** [comment]
@carmodyquinnms  - should this file have been put into the workflows directory "[.CreateIngressCert.yml.swp](https://github.com/Azure/aks-baseline-automation/pull/54/files#diff-7c26827e9cf8e964f69b3efae295b19349d4fdf4b1930656848269b50785b10a)" - looks odd.

**Comment by carmodyquinnms** [comment]
@Gordon ***@***.***> sorry - that should not have been added.  That is my vi swap file and I need to delete it (and update .ignore with *.swp)

[Icon  Description automatically generated]
Carmody Quinn
Microsoft Consulting Services
Azure Cloud & AI Delivery
Mobile:  +1 (832) 252-4451
Email: ***@***.******@***.***>
https://www.linkedin.com/in/carmodyquinn/

**Comment by Gordonby** [comment]
Don't worry, i don't blame you @carmodyquinnms - it's all the approvers fault.... @MattLeach25 !!!!! 😉

**Comment by carmodyquinnms** [comment]
Good!! So long as I can blame someone else – LOL!! Yeah I think where @Matthew ***@***.***> mess up was by trusting me 😉

[Icon  Description automatically generated]
Carmody Quinn
Microsoft Consulting Services
Azure Cloud & AI Delivery
Mobile:  +1 (832) 252-4451
Email: ***@***.******@***.***>
https://www.linkedin.com/in/carmodyquinn/

**Pull request merged**
