### PR TITLE
Updated az cli query command to correspond to the latest JSON schema.…

### PR DESCRIPTION
**Pull request by oliverlabs**
… The old one deprecated.

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [x] This PR is ready to merge and is not **Work in Progress**
- [ ] Link to a filed issue

### CODE REVIEW

**Review by bahramr — COMMENTED** [review]
I don't see the difference. Did you just change ObjectOD to ID? What does that have to do with the schema?

**Comment by oliverlabs** [comment]
Hi @bahramr, have you actually ran the command? The difference is my code works as it correctly corresponds to the JSON schema of the az ad cli and the existing command in the GH repository does not return anything and is broken.

**Comment by oliverlabs** [comment]
Any updates on this, @bahramr @asw101 @jacqinthebox @jgardner04 ?

**Comment by mosabami** [comment]
thanks for your contribution @oliverlabs. Merging

**Review by mosabami — APPROVED** [review]

**Pull request merged**
